

services:
  client-gateway:
    build: ./client-gateway
    ports:
      - "4000:4000"
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=4000
      - NATS_SERVERS=nats://localhost:4222