
services:
  tasks-db:
    image: postgres:15.3
    container_name: taks-database
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: "Etc/UTC"
    ports:
      - "5433:5432"
    volumes:
      - ./postgres:/var/lib/postgresql/data